# Source Generated with Decompyle++
# File: admin_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_adminForm(object):
    def setupUi(self, adminForm):
        adminForm.setObjectName('adminForm')
        adminForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(adminForm.minimumSizeHint()))
        adminForm.setMinimumSize(QtCore.QSize(768, 1024))
        adminForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        adminForm.setPalette(palette)
        adminForm.setAutoFillBackground(True)
        self.txt_admin_label = QtGui.QLabel(adminForm)
        self.txt_admin_label.setGeometry(QtCore.QRect(30, 20, 481, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_admin_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_admin_label.setFont(font)
        self.txt_admin_label.setObjectName('txt_admin_label')
        self.layoutWidget = QtGui.QWidget(adminForm)
        self.layoutWidget.setGeometry(QtCore.QRect(51, 464, 669, 131))
        self.layoutWidget.setObjectName('layoutWidget')
        self.hboxlayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.hboxlayout.setSpacing(5)
        self.hboxlayout.setObjectName('hboxlayout')
        self.layoutWidget1 = QtGui.QWidget(adminForm)
        self.layoutWidget1.setGeometry(QtCore.QRect(51, 210, 669, 141))
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.hboxlayout1 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.hboxlayout1.setSpacing(5)
        self.hboxlayout1.setObjectName('hboxlayout1')
        self.layoutWidget2 = QtGui.QWidget(adminForm)
        self.layoutWidget2.setGeometry(QtCore.QRect(51, 710, 669, 141))
        self.layoutWidget2.setObjectName('layoutWidget2')
        self.hboxlayout2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.hboxlayout2.setSpacing(5)
        self.hboxlayout2.setObjectName('hboxlayout2')
        self.retranslateUi(adminForm)
        QtCore.QMetaObject.connectSlotsByName(adminForm)

    
    def retranslateUi(self, adminForm):
        self.txt_admin_label.setText(QtGui.QApplication.translate('adminForm', 'Admin', None, QtGui.QApplication.UnicodeUTF8))


