# Source Generated with Decompyle++
# File: info_component.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui
import sys
import config

class Information(QtGui.QWidget):
    
    def __init__(self, parent = None):
        QtGui.QWidget.__init__(self, parent)
        self.horizontalLayout = QtGui.QWidget(self)
        self.horizontalLayout.setGeometry(QtCore.QRect(10, 0, 511, 51))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.kiosk_id_label = QtGui.QLabel(self.horizontalLayout)
        self.kiosk_id_label.setMaximumSize(QtCore.QSize(40, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id_label.setFont(font)
        self.hboxlayout.addWidget(self.kiosk_id_label)
        self.kiosk_id = QtGui.QLabel(self.horizontalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id.setFont(font)
        self.kiosk_id.setObjectName('kiosk_id')
        self.hboxlayout.addWidget(self.kiosk_id)
        self.kiosk_id_label_5 = QtGui.QLabel(self.horizontalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id_label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id_label_5.setFont(font)
        self.hboxlayout.addWidget(self.kiosk_id_label_5)
        self.kiosk_id_label_3 = QtGui.QLabel(self.horizontalLayout)
        self.kiosk_id_label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id_label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id_label_3.setFont(font)
        self.hboxlayout.addWidget(self.kiosk_id_label_3)
        self.capacity = QtGui.QLabel(self.horizontalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.capacity.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.capacity.setFont(font)
        self.capacity.setObjectName('capacity')
        self.hboxlayout.addWidget(self.capacity)
        self.frame = QtGui.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(6, 75, 639, 500))
        self.verticalLayout = QtGui.QWidget(self.frame)
        self.verticalLayout.setGeometry(QtCore.QRect(29, 49, 580, 401))
        self.vboxlayout = QtGui.QVBoxLayout(self.verticalLayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.label_2 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.hboxlayout1.addWidget(self.label_2)
        self.firmware = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.firmware.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.firmware.setFont(font)
        self.firmware.setObjectName('firmware')
        self.hboxlayout1.addWidget(self.firmware)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.label_5 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.hboxlayout2.addWidget(self.label_5)
        self.ip = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ip.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.ip.setFont(font)
        self.ip.setObjectName('ip')
        self.hboxlayout2.addWidget(self.ip)
        self.vboxlayout.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.label_14 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.hboxlayout3.addWidget(self.label_14)
        self.external_ip = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.external_ip.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.external_ip.setFont(font)
        self.external_ip.setObjectName('external_ip')
        self.hboxlayout3.addWidget(self.external_ip)
        self.vboxlayout.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.label_6 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.hboxlayout4.addWidget(self.label_6)
        self.kiosk_id2 = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id2.setFont(font)
        self.kiosk_id2.setObjectName('kiosk_id2')
        self.hboxlayout4.addWidget(self.kiosk_id2)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.label_7 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.hboxlayout5.addWidget(self.label_7)
        self.kiosk_soft = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_soft.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_soft.setFont(font)
        self.kiosk_soft.setObjectName('kiosk_soft')
        self.hboxlayout5.addWidget(self.kiosk_soft)
        self.vboxlayout.addLayout(self.hboxlayout5)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.label_8 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.hboxlayout6.addWidget(self.label_8)
        self.mac = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.mac.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.mac.setFont(font)
        self.mac.setObjectName('mac')
        self.hboxlayout6.addWidget(self.mac)
        self.vboxlayout.addLayout(self.hboxlayout6)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.label_16 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.hboxlayout7.addWidget(self.label_16)
        self.start_time = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.start_time.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.start_time.setFont(font)
        self.start_time.setObjectName('start_time')
        self.hboxlayout7.addWidget(self.start_time)
        self.vboxlayout.addLayout(self.hboxlayout7)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.label_18 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.hboxlayout8.addWidget(self.label_18)
        self.kiosk_time_zone = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_time_zone.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_time_zone.setFont(font)
        self.kiosk_time_zone.setObjectName('kiosk_time_zone')
        self.hboxlayout8.addWidget(self.kiosk_time_zone)
        self.vboxlayout.addLayout(self.hboxlayout8)
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.label_9 = QtGui.QLabel(self.verticalLayout)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.hboxlayout9.addWidget(self.label_9)
        self.umg_channel = QtGui.QLabel(self.verticalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.umg_channel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.umg_channel.setFont(font)
        self.umg_channel.setObjectName('umg_channel')
        self.hboxlayout9.addWidget(self.umg_channel)
        self.vboxlayout.addLayout(self.hboxlayout9)
        self.label_today = QtGui.QLabel(self.frame)
        self.label_today.setGeometry(QtCore.QRect(400, 0, 120, 51))
        self.label_today.setStyleSheet('color: white; font: bold 22px;')
        self.label_today.setAlignment(QtCore.Qt.AlignCenter)
        self.today = QtGui.QLabel(self.frame)
        self.today.setGeometry(QtCore.QRect(520, 0, 200, 51))
        self.today.setStyleSheet('color: white; font: bold 22px;')
        self.retranslateUi(parent)

    
    def retranslateUi(self, Form):
        self.kiosk_id_label.setText(QtGui.QApplication.translate('Form', 'ID: ', None, QtGui.QApplication.UnicodeUTF8))
        self.kiosk_id_label_3.setText(QtGui.QApplication.translate('Form', 'Capacity: ', None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate('Form', 'Firmware:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate('Form', 'IP:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate('Form', 'External IP:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate('Form', 'KioskID:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate('Form', 'KioskSoft:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate('Form', 'MAC:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate('Form', 'Start Time:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate('Form', 'Time Zone:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate('Form', 'UMG Channel:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_today.setText(QtGui.QApplication.translate('Form', 'Today: ', None, QtGui.QApplication.UnicodeUTF8))

    
    def setReport(self, data):
        if not data or not data['ctr_information']:
            return None
        
        data = data['ctr_information']
        for key in data:
            exec('self.' + key + '.setText("' + data[key] + '")')
        
        self.kiosk_id2.setText(self.kiosk_id.text())



class myForm(QtGui.QWidget):
    
    def __init__(self, parent = None):
        QtGui.QWidget.__init__(self, parent)
        self.setGeometry(0, 0, 768, 1000)
        palette = QtGui.QPalette()
        palette.setBrush(self.backgroundRole(), QtGui.QBrush(QtGui.QPixmap(config.pic_bg_load)))
        self.setPalette(palette)

    
    def test(self):
        info = Information(self)
        info.setGeometry(10, 10, 650, 600)
        data = {
            'ctr_information': {
                'kiosk_id': 'LAKSJDF09',
                'capacity': 'CASDF',
                'today': '2009-8-8',
                'firmware': 'ASDF',
                'ip': '192.168.14.1',
                'external_ip': '192.168.14.2',
                'kiosk_id2': 'KSJ89',
                'kiosk_soft': 'ASDF',
                'mac': '2983SAFS',
                'start_time': '2009-8-8',
                'kiosk_time_zone': '2009-8-8',
                'umg_channel': 'ASDFAS' } }
        info.setReport(data)
        info.show()


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    mainf = myForm()
    mainf.test()
    mainf.show()
    sys.exit(app.exec_())

