# Source Generated with Decompyle++
# File: loadDiscInfoForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_loadDiskInfoForm(object):
    
    def setupUi(self, loadDiskInfoForm):
        loadDiskInfoForm.setObjectName('loadDiskInfoForm')
        loadDiskInfoForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(loadDiskInfoForm.minimumSizeHint()))
        loadDiskInfoForm.setMinimumSize(QtCore.QSize(768, 1024))
        loadDiskInfoForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        loadDiskInfoForm.setPalette(palette)
        loadDiskInfoForm.setAutoFillBackground(True)
        self.txt_load_label = QtGui.QLabel(loadDiskInfoForm)
        self.txt_load_label.setGeometry(QtCore.QRect(50, 30, 221, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_load_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_load_label.setFont(font)
        self.txt_load_label.setObjectName('txt_load_label')
        self.horizontalLayout = QtGui.QWidget(loadDiskInfoForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(50, 910, 661, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setSpacing(50)
        self.hboxlayout.setObjectName('hboxlayout')
        self.movie_title = QtGui.QLabel(loadDiskInfoForm)
        self.movie_title.setGeometry(QtCore.QRect(68, 110, 651, 60))
        self.movie_title.setMaximumSize(QtCore.QSize(669, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.movie_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setWeight(75)
        font.setBold(True)
        self.movie_title.setFont(font)
        self.movie_title.setWordWrap(True)
        self.movie_title.setObjectName('movie_title')
        self.horizontalLayout_2 = QtGui.QWidget(loadDiskInfoForm)
        self.horizontalLayout_2.setGeometry(QtCore.QRect(60, 190, 691, 179))
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.hboxlayout1 = QtGui.QHBoxLayout(self.horizontalLayout_2)
        self.hboxlayout1.setSpacing(12)
        self.hboxlayout1.setObjectName('hboxlayout1')
        self.movie_pic = QtGui.QLabel(self.horizontalLayout_2)
        self.movie_pic.setMinimumSize(QtCore.QSize(100, 150))
        self.movie_pic.setMaximumSize(QtCore.QSize(100, 150))
        self.movie_pic.setScaledContents(True)
        self.movie_pic.setObjectName('movie_pic')
        self.hboxlayout1.addWidget(self.movie_pic)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setHorizontalSpacing(5)
        self.gridlayout.setVerticalSpacing(0)
        self.gridlayout.setObjectName('gridlayout')
        self.label_21 = QtGui.QLabel(self.horizontalLayout_2)
        self.label_21.setMaximumSize(QtCore.QSize(180, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName('label_21')
        self.gridlayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.directors = QtGui.QLabel(self.horizontalLayout_2)
        self.directors.setMinimumSize(QtCore.QSize(390, 50))
        self.directors.setMaximumSize(QtCore.QSize(390, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.directors.setFont(font)
        self.directors.setWordWrap(True)
        self.directors.setObjectName('directors')
        self.gridlayout.addWidget(self.directors, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.horizontalLayout_2)
        self.label_22.setMinimumSize(QtCore.QSize(180, 25))
        self.label_22.setMaximumSize(QtCore.QSize(180, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_22.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName('label_22')
        self.gridlayout.addWidget(self.label_22, 1, 0, 1, 1)
        self.rating = QtGui.QLabel(self.horizontalLayout_2)
        self.rating.setMinimumSize(QtCore.QSize(0, 25))
        self.rating.setMaximumSize(QtCore.QSize(390, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.rating.setFont(font)
        self.rating.setObjectName('rating')
        self.gridlayout.addWidget(self.rating, 1, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.horizontalLayout_2)
        self.label_23.setMinimumSize(QtCore.QSize(180, 25))
        self.label_23.setMaximumSize(QtCore.QSize(180, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName('label_23')
        self.gridlayout.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.horizontalLayout_2)
        self.label_24.setMinimumSize(QtCore.QSize(180, 25))
        self.label_24.setMaximumSize(QtCore.QSize(180, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_24.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName('label_24')
        self.gridlayout.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.horizontalLayout_2)
        self.label_25.setMinimumSize(QtCore.QSize(180, 25))
        self.label_25.setMaximumSize(QtCore.QSize(180, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_25.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_25.setObjectName('label_25')
        self.gridlayout.addWidget(self.label_25, 4, 0, 1, 1)
        self.genre = QtGui.QLabel(self.horizontalLayout_2)
        self.genre.setMinimumSize(QtCore.QSize(0, 25))
        self.genre.setMaximumSize(QtCore.QSize(390, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.genre.setFont(font)
        self.genre.setObjectName('genre')
        self.gridlayout.addWidget(self.genre, 2, 1, 1, 1)
        self.dvd_release_date = QtGui.QLabel(self.horizontalLayout_2)
        self.dvd_release_date.setMinimumSize(QtCore.QSize(0, 25))
        self.dvd_release_date.setMaximumSize(QtCore.QSize(390, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.dvd_release_date.setFont(font)
        self.dvd_release_date.setObjectName('dvd_release_date')
        self.gridlayout.addWidget(self.dvd_release_date, 3, 1, 1, 1)
        self.starring = QtGui.QLabel(self.horizontalLayout_2)
        self.starring.setMinimumSize(QtCore.QSize(0, 50))
        self.starring.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.starring.setFont(font)
        self.starring.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.starring.setWordWrap(True)
        self.starring.setObjectName('starring')
        self.gridlayout.addWidget(self.starring, 4, 1, 1, 1)
        self.hboxlayout1.addLayout(self.gridlayout)
        self.dvd_version = QtGui.QLabel(loadDiskInfoForm)
        self.dvd_version.setGeometry(QtCore.QRect(68, 170, 381, 20))
        self.dvd_version.setMaximumSize(QtCore.QSize(16777215, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.dvd_version.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dvd_version.setFont(font)
        self.dvd_version.setObjectName('dvd_version')
        self.retranslateUi(loadDiskInfoForm)
        QtCore.QMetaObject.connectSlotsByName(loadDiskInfoForm)

    
    def retranslateUi(self, loadDiskInfoForm):
        self.txt_load_label.setText(QtGui.QApplication.translate('loadDiskInfoForm', 'Load', None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate('loadDiskInfoForm', 'Directors:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate('loadDiskInfoForm', 'Rating:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate('loadDiskInfoForm', 'Genre:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate('loadDiskInfoForm', 'DVD Release Date:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate('loadDiskInfoForm', 'Starring:', None, QtGui.QApplication.UnicodeUTF8))


