# Source Generated with Decompyle++
# File: loadDiscListForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_loadDiscListForm(object):
    
    def setupUi(self, loadDiscListForm):
        loadDiscListForm.setObjectName('loadDiscListForm')
        loadDiscListForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(loadDiscListForm.minimumSizeHint()))
        loadDiscListForm.setMinimumSize(QtCore.QSize(768, 1024))
        loadDiscListForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        loadDiscListForm.setPalette(palette)
        loadDiscListForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        loadDiscListForm.setAutoFillBackground(True)
        self.txt_load_label = QtGui.QLabel(loadDiscListForm)
        self.txt_load_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_load_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_load_label.setFont(font)
        self.txt_load_label.setObjectName('txt_load_label')
        self.horizontalLayout = QtGui.QWidget(loadDiscListForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(40, 910, 691, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.key_label = QtGui.QLabel(loadDiscListForm)
        self.key_label.setGeometry(QtCore.QRect(50, 120, 121, 38))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.key_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.key_label.setFont(font)
        self.key_label.setScaledContents(False)
        self.key_label.setObjectName('key_label')
        self.txtbox_key = QtGui.QLabel(loadDiscListForm)
        self.txtbox_key.setGeometry(QtCore.QRect(180, 120, 491, 38))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_key.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txtbox_key.setFont(font)
        self.txtbox_key.setScaledContents(False)
        self.txtbox_key.setObjectName('txtbox_key')
        self.txt_found = QtGui.QLabel(loadDiscListForm)
        self.txt_found.setGeometry(QtCore.QRect(50, 840, 71, 42))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_found.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txt_found.setFont(font)
        self.txt_found.setScaledContents(False)
        self.txt_found.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_found.setObjectName('txt_found')
        self.txt_found_label = QtGui.QLabel(loadDiscListForm)
        self.txt_found_label.setGeometry(QtCore.QRect(120, 840, 441, 38))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_found_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txt_found_label.setFont(font)
        self.txt_found_label.setScaledContents(False)
        self.txt_found_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.txt_found_label.setObjectName('txt_found_label')
        self.retranslateUi(loadDiscListForm)
        QtCore.QMetaObject.connectSlotsByName(loadDiscListForm)

    
    def retranslateUi(self, loadDiscListForm):
        self.txt_load_label.setText(QtGui.QApplication.translate('loadDiscListForm', 'Load', None, QtGui.QApplication.UnicodeUTF8))
        self.key_label.setText(QtGui.QApplication.translate('loadDiscListForm', 'Search:', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_found_label.setText(QtGui.QApplication.translate('loadDiscListForm', 'movies found', None, QtGui.QApplication.UnicodeUTF8))


