# Source Generated with Decompyle++
# File: load_title_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_loadTitleForm(object):
    
    def setupUi(self, loadTitleForm):
        loadTitleForm.setObjectName('loadTitleForm')
        loadTitleForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(loadTitleForm.minimumSizeHint()))
        loadTitleForm.setMinimumSize(QtCore.QSize(768, 1024))
        loadTitleForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        loadTitleForm.setPalette(palette)
        loadTitleForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        loadTitleForm.setAutoFillBackground(True)
        self.txt_load_label = QtGui.QLabel(loadTitleForm)
        self.txt_load_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_load_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_load_label.setFont(font)
        self.txt_load_label.setObjectName('txt_load_label')
        self.horizontalLayout = QtGui.QWidget(loadTitleForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(40, 910, 691, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.txtbox_msg = QtGui.QLabel(loadTitleForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(140, 240, 501, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setScaledContents(False)
        self.txtbox_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtbox_msg.setObjectName('txtbox_msg')
        self.retranslateUi(loadTitleForm)
        QtCore.QMetaObject.connectSlotsByName(loadTitleForm)

    
    def retranslateUi(self, loadTitleForm):
        self.txt_load_label.setText(QtGui.QApplication.translate('loadTitleForm', 'Load', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg.setText(QtGui.QApplication.translate('loadTitleForm', 'Please enter the movie title', None, QtGui.QApplication.UnicodeUTF8))


