# Source Generated with Decompyle++
# File: movie_detail_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_MovieDetailForm(object):
    
    def setupUi(self, MovieDetailForm):
        MovieDetailForm.setObjectName('MovieDetailForm')
        MovieDetailForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(MovieDetailForm.minimumSizeHint()))
        MovieDetailForm.setMinimumSize(QtCore.QSize(768, 1024))
        MovieDetailForm.setMaximumSize(QtCore.QSize(768, 1024))
        MovieDetailForm.setCursor(QtCore.Qt.BlankCursor)
        MovieDetailForm.setAutoFillBackground(True)
        self.txt_detail_label = QtGui.QLabel(MovieDetailForm)
        self.txt_detail_label.setGeometry(QtCore.QRect(50, 30, 461, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_detail_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_detail_label.setFont(font)
        self.txt_detail_label.setObjectName('txt_detail_label')
        self.horizontalLayout = QtGui.QWidget(MovieDetailForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(50, 910, 661, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setSpacing(50)
        self.hboxlayout.setObjectName('hboxlayout')
        self.label_15 = QtGui.QLabel(MovieDetailForm)
        self.label_15.setGeometry(QtCore.QRect(50, 581, 271, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_15.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName('label_15')
        self.synopsis = QtGui.QTextEdit(MovieDetailForm)
        self.synopsis.setEnabled(True)
        self.synopsis.setGeometry(QtCore.QRect(50, 621, 321, 241))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.synopsis.setFont(font)
        self.synopsis.setProperty('cursor', QtCore.QVariant(QtCore.Qt.BlankCursor))
        self.synopsis.setFocusPolicy(QtCore.Qt.NoFocus)
        self.synopsis.setAcceptDrops(False)
        self.synopsis.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.synopsis.setUndoRedoEnabled(False)
        self.synopsis.setReadOnly(True)
        self.synopsis.setCursorWidth(0)
        self.synopsis.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.synopsis.setObjectName('synopsis')
        self.frame_2 = QtGui.QFrame(MovieDetailForm)
        self.frame_2.setGeometry(QtCore.QRect(50, 195, 661, 221))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setObjectName('frame_2')
        self.frame_3 = QtGui.QFrame(MovieDetailForm)
        self.frame_3.setGeometry(QtCore.QRect(50, 435, 661, 111))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setObjectName('frame_3')
        self.mask_coming_soon_flag = QtGui.QLabel(MovieDetailForm)
        self.mask_coming_soon_flag.setGeometry(QtCore.QRect(45, 325, 678, 378))
        self.mask_coming_soon_flag.setObjectName('mask_coming_soon_flag')
        self.frame = QtGui.QFrame(MovieDetailForm)
        self.frame.setGeometry(QtCore.QRect(390, 620, 321, 241))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName('frame')
        self.icon_dvd = QtGui.QLabel(MovieDetailForm)
        self.icon_dvd.setGeometry(QtCore.QRect(65, 360, 100, 45))
        self.icon_dvd.setObjectName('icon_dvd')
        self.movie_pic = QtGui.QLabel(MovieDetailForm)
        self.movie_pic.setGeometry(QtCore.QRect(65, 205, 100, 150))
        self.movie_pic.setMinimumSize(QtCore.QSize(100, 150))
        self.movie_pic.setMaximumSize(QtCore.QSize(100, 150))
        self.movie_pic.setScaledContents(True)
        self.movie_pic.setObjectName('movie_pic')
        self.dvd_version = QtGui.QLabel(MovieDetailForm)
        self.dvd_version.setGeometry(QtCore.QRect(65, 166, 260, 25))
        self.dvd_version.setMinimumSize(QtCore.QSize(260, 25))
        self.dvd_version.setMaximumSize(QtCore.QSize(260, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.dvd_version.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dvd_version.setFont(font)
        self.dvd_version.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.dvd_version.setObjectName('dvd_version')
        self.movie_title = QtGui.QLabel(MovieDetailForm)
        self.movie_title.setGeometry(QtCore.QRect(50, 111, 661, 60))
        self.movie_title.setMaximumSize(QtCore.QSize(661, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.movie_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setWeight(75)
        font.setBold(True)
        self.movie_title.setFont(font)
        self.movie_title.setWordWrap(True)
        self.movie_title.setObjectName('movie_title')
        self.layoutWidget = QtGui.QWidget(MovieDetailForm)
        self.layoutWidget.setGeometry(QtCore.QRect(48, 439, 661, 101))
        self.layoutWidget.setObjectName('layoutWidget')
        self.hboxlayout1 = QtGui.QHBoxLayout(self.layoutWidget)
        self.hboxlayout1.setSpacing(10)
        self.hboxlayout1.setObjectName('hboxlayout1')
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName('label_10')
        self.hboxlayout1.addWidget(self.label_10)
        self.rent_price = QtGui.QLabel(self.layoutWidget)
        self.rent_price.setMinimumSize(QtCore.QSize(50, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rent_price.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('URW Bookman L')
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.rent_price.setFont(font)
        self.rent_price.setObjectName('rent_price')
        self.hboxlayout1.addWidget(self.rent_price)
        self.label_buy = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.label_buy.setFont(font)
        self.label_buy.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_buy.setObjectName('label_buy')
        self.hboxlayout1.addWidget(self.label_buy)
        self.buy_price = QtGui.QLabel(self.layoutWidget)
        self.buy_price.setMinimumSize(QtCore.QSize(50, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.buy_price.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('URW Bookman L')
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.buy_price.setFont(font)
        self.buy_price.setObjectName('buy_price')
        self.hboxlayout1.addWidget(self.buy_price)
        self.retranslateUi(MovieDetailForm)
        QtCore.QMetaObject.connectSlotsByName(MovieDetailForm)

    
    def retranslateUi(self, MovieDetailForm):
        self.txt_detail_label.setText(QtGui.QApplication.translate('MovieDetailForm', 'Details', None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate('MovieDetailForm', 'Synopsis:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate('MovieDetailForm', 'Rent:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_buy.setText(QtGui.QApplication.translate('MovieDetailForm', 'Buy:', None, QtGui.QApplication.UnicodeUTF8))


