# Source Generated with Decompyle++
# File: pickupDiscListForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_pickupDiskInfoForm(object):
    
    def setupUi(self, pickupDiskInfoForm):
        pickupDiskInfoForm.setObjectName('pickupDiskInfoForm')
        pickupDiskInfoForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(pickupDiskInfoForm.minimumSizeHint()))
        pickupDiskInfoForm.setMinimumSize(QtCore.QSize(768, 1024))
        pickupDiskInfoForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        pickupDiskInfoForm.setPalette(palette)
        pickupDiskInfoForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        pickupDiskInfoForm.setAutoFillBackground(True)
        self.txt_pick_label = QtGui.QLabel(pickupDiskInfoForm)
        self.txt_pick_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_pick_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_pick_label.setFont(font)
        self.txt_pick_label.setObjectName('txt_pick_label')
        self.horizontalLayout = QtGui.QWidget(pickupDiskInfoForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(40, 920, 691, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.txtbox_msg = QtGui.QLabel(pickupDiskInfoForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(60, 137, 571, 118))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setScaledContents(False)
        self.txtbox_msg.setWordWrap(True)
        self.txtbox_msg.setObjectName('txtbox_msg')
        self.retranslateUi(pickupDiskInfoForm)
        QtCore.QMetaObject.connectSlotsByName(pickupDiskInfoForm)

    
    def retranslateUi(self, pickupDiskInfoForm):
        self.txt_pick_label.setText(QtGui.QApplication.translate('pickupDiskInfoForm', 'Pick Up', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg.setText(QtGui.QApplication.translate('pickupDiskInfoForm', 'Disc(s) You Reserved', None, QtGui.QApplication.UnicodeUTF8))


