# Source Generated with Decompyle++
# File: pickupEjectForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_pickupEjectForm(object):
    
    def setupUi(self, pickupEjectForm):
        pickupEjectForm.setObjectName('pickupEjectForm')
        pickupEjectForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(pickupEjectForm.minimumSizeHint()))
        pickupEjectForm.setMinimumSize(QtCore.QSize(768, 1024))
        pickupEjectForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        pickupEjectForm.setPalette(palette)
        pickupEjectForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        pickupEjectForm.setAutoFillBackground(True)
        self.txt_pick_label = QtGui.QLabel(pickupEjectForm)
        self.txt_pick_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_pick_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_pick_label.setFont(font)
        self.txt_pick_label.setObjectName('txt_pick_label')
        self.txtbox_msg1 = QtGui.QLabel(pickupEjectForm)
        self.txtbox_msg1.setGeometry(QtCore.QRect(90, 160, 91, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg1.setFont(font)
        self.txtbox_msg1.setScaledContents(False)
        self.txtbox_msg1.setWordWrap(True)
        self.txtbox_msg1.setObjectName('txtbox_msg1')
        self.swf_bar = QtGui.QLabel(pickupEjectForm)
        self.swf_bar.setGeometry(QtCore.QRect(130, 940, 501, 31))
        self.swf_bar.setObjectName('swf_bar')
        self.txt_total = QtGui.QLabel(pickupEjectForm)
        self.txt_total.setGeometry(QtCore.QRect(190, 160, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_total.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txt_total.setFont(font)
        self.txt_total.setScaledContents(False)
        self.txt_total.setWordWrap(True)
        self.txt_total.setObjectName('txt_total')
        self.txtbox_msg_3 = QtGui.QLabel(pickupEjectForm)
        self.txtbox_msg_3.setGeometry(QtCore.QRect(240, 160, 251, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg_3.setFont(font)
        self.txtbox_msg_3.setScaledContents(False)
        self.txtbox_msg_3.setWordWrap(True)
        self.txtbox_msg_3.setObjectName('txtbox_msg_3')
        self.txtbox_msg_4 = QtGui.QLabel(pickupEjectForm)
        self.txtbox_msg_4.setGeometry(QtCore.QRect(90, 210, 241, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg_4.setFont(font)
        self.txtbox_msg_4.setScaledContents(False)
        self.txtbox_msg_4.setWordWrap(True)
        self.txtbox_msg_4.setObjectName('txtbox_msg_4')
        self.txt_taked = QtGui.QLabel(pickupEjectForm)
        self.txt_taked.setGeometry(QtCore.QRect(340, 210, 51, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_taked.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txt_taked.setFont(font)
        self.txt_taked.setScaledContents(False)
        self.txt_taked.setWordWrap(True)
        self.txt_taked.setObjectName('txt_taked')
        self.txtbox_msg_6 = QtGui.QLabel(pickupEjectForm)
        self.txtbox_msg_6.setGeometry(QtCore.QRect(390, 210, 211, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg_6.setFont(font)
        self.txtbox_msg_6.setScaledContents(False)
        self.txtbox_msg_6.setWordWrap(True)
        self.txtbox_msg_6.setObjectName('txtbox_msg_6')
        self.txtbox_msg_7 = QtGui.QLabel(pickupEjectForm)
        self.txtbox_msg_7.setGeometry(QtCore.QRect(140, 260, 461, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg_7.setFont(font)
        self.txtbox_msg_7.setScaledContents(False)
        self.txtbox_msg_7.setWordWrap(True)
        self.txtbox_msg_7.setObjectName('txtbox_msg_7')
        self.txt_processing = QtGui.QLabel(pickupEjectForm)
        self.txt_processing.setGeometry(QtCore.QRect(90, 260, 51, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_processing.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txt_processing.setFont(font)
        self.txt_processing.setScaledContents(False)
        self.txt_processing.setWordWrap(True)
        self.txt_processing.setObjectName('txt_processing')
        self.txtbox_msg = QtGui.QLabel(pickupEjectForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(90, 310, 591, 85))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 102, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(23)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setScaledContents(False)
        self.txtbox_msg.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.txtbox_msg.setWordWrap(True)
        self.txtbox_msg.setObjectName('txtbox_msg')
        self.retranslateUi(pickupEjectForm)
        QtCore.QMetaObject.connectSlotsByName(pickupEjectForm)

    
    def retranslateUi(self, pickupEjectForm):
        self.txt_pick_label.setText(QtGui.QApplication.translate('pickupEjectForm', 'Pick Up', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg1.setText(QtGui.QApplication.translate('pickupEjectForm', 'Total: ', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_total.setText(QtGui.QApplication.translate('pickupEjectForm', '1', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg_3.setText(QtGui.QApplication.translate('pickupEjectForm', 'DVD(s)', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg_4.setText(QtGui.QApplication.translate('pickupEjectForm', 'You have taken ', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_taked.setText(QtGui.QApplication.translate('pickupEjectForm', '1', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg_6.setText(QtGui.QApplication.translate('pickupEjectForm', 'DVD(s)', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg_7.setText(QtGui.QApplication.translate('pickupEjectForm', 'DVD(s) is processing', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_processing.setText(QtGui.QApplication.translate('pickupEjectForm', '1', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg.setText(QtGui.QApplication.translate('pickupEjectForm', 'Please wait for next one', None, QtGui.QApplication.UnicodeUTF8))


