# Source Generated with Decompyle++
# File: registerMainForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_registerMainForm(object):
    
    def setupUi(self, registerMainForm):
        registerMainForm.setObjectName('registerMainForm')
        registerMainForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(registerMainForm.minimumSizeHint()))
        registerMainForm.setMinimumSize(QtCore.QSize(768, 1024))
        registerMainForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        registerMainForm.setPalette(palette)
        registerMainForm.setAutoFillBackground(True)
        self.info_msg = QtGui.QLabel(registerMainForm)
        self.info_msg.setGeometry(QtCore.QRect(90, 160, 571, 100))
        self.info_msg.setWordWrap(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.info_msg.setPalette(palette)
        self.txt_card_label = QtGui.QLabel(registerMainForm)
        self.txt_card_label.setGeometry(QtCore.QRect(50, 30, 520, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_card_label.setPalette(palette)
        self.txtbox_msg = QtGui.QLabel(registerMainForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(90, 275, 571, 71))
        self.txtbox_msg.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.info_msg.setFont(font)
        self.info_msg.setObjectName('info_msg')
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setObjectName('txtbox_msg')
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_card_label.setFont(font)
        self.txt_card_label.setObjectName('txt_card_label')
        self.swf_credit_cars = QtGui.QLabel(registerMainForm)
        self.swf_credit_cars.setGeometry(QtCore.QRect(103, 260, 541, 101))
        self.swf_credit_cars.setObjectName('swf_credit_cars')
        self.horizontalLayout = QtGui.QWidget(registerMainForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(50, 920, 671, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.retranslateUi(registerMainForm)
        QtCore.QMetaObject.connectSlotsByName(registerMainForm)

    
    def retranslateUi(self, registerMainForm):
        self.txt_card_label.setText(QtGui.QApplication.translate('registerMainForm', 'Membership Card Registration', None, QtGui.QApplication.UnicodeUTF8))
        self.info_msg.setText(QtGui.QApplication.translate('registerMainForm', 'Please register your new cerepay card for security reason. A membership account will be set up and blinded automatically.', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg.setText(QtGui.QApplication.translate('registerMainForm', 'Please enter your email address.', None, QtGui.QApplication.UnicodeUTF8))


