# Source Generated with Decompyle++
# File: reportForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_reportForm(object):
    
    def setupUi(self, reportForm):
        reportForm.setObjectName('reportForm')
        reportForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 996).size()).expandedTo(reportForm.minimumSizeHint()))
        reportForm.setAutoFillBackground(True)
        self.horizontalLayout = QtGui.QWidget(reportForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(70, 130, 541, 51))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.kiosk_id_label = QtGui.QLabel(self.horizontalLayout)
        self.kiosk_id_label.setMaximumSize(QtCore.QSize(40, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id_label.setFont(font)
        self.kiosk_id_label.setObjectName('kiosk_id_label')
        self.hboxlayout.addWidget(self.kiosk_id_label)
        self.kiosk_id = QtGui.QLabel(self.horizontalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id.setFont(font)
        self.kiosk_id.setObjectName('kiosk_id')
        self.hboxlayout.addWidget(self.kiosk_id)
        self.kiosk_id_label_5 = QtGui.QLabel(self.horizontalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id_label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id_label_5.setFont(font)
        self.kiosk_id_label_5.setObjectName('kiosk_id_label_5')
        self.hboxlayout.addWidget(self.kiosk_id_label_5)
        self.kiosk_id_label_3 = QtGui.QLabel(self.horizontalLayout)
        self.kiosk_id_label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kiosk_id_label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.kiosk_id_label_3.setFont(font)
        self.kiosk_id_label_3.setObjectName('kiosk_id_label_3')
        self.hboxlayout.addWidget(self.kiosk_id_label_3)
        self.capacity = QtGui.QLabel(self.horizontalLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.capacity.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.capacity.setFont(font)
        self.capacity.setObjectName('capacity')
        self.hboxlayout.addWidget(self.capacity)
        self.txt_pick_label = QtGui.QLabel(reportForm)
        self.txt_pick_label.setGeometry(QtCore.QRect(60, 40, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_pick_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_pick_label.setFont(font)
        self.txt_pick_label.setObjectName('txt_pick_label')
        self.gridLayout = QtGui.QWidget(reportForm)
        self.gridLayout.setGeometry(QtCore.QRect(60, 240, 661, 181))
        self.gridLayout.setObjectName('gridLayout')
        self.gridlayout = QtGui.QGridLayout(self.gridLayout)
        self.gridlayout.setObjectName('gridlayout')
        self.label = QtGui.QLabel(self.gridLayout)
        self.label.setObjectName('label')
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.completed_rentals = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.completed_rentals.setPalette(palette)
        self.completed_rentals.setObjectName('completed_rentals')
        self.gridlayout.addWidget(self.completed_rentals, 0, 1, 1, 1)
        self.today = QtGui.QLabel(self.gridLayout)
        self.today.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.today.setPalette(palette)
        self.today.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.today.setObjectName('today')
        self.gridlayout.addWidget(self.today, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayout)
        self.label_5.setObjectName('label_5')
        self.gridlayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.rental_income = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rental_income.setPalette(palette)
        self.rental_income.setObjectName('rental_income')
        self.gridlayout.addWidget(self.rental_income, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayout)
        self.label_7.setObjectName('label_7')
        self.gridlayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.initial_rentals = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.initial_rentals.setPalette(palette)
        self.initial_rentals.setObjectName('initial_rentals')
        self.gridlayout.addWidget(self.initial_rentals, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayout)
        self.label_9.setObjectName('label_9')
        self.gridlayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.sale_count = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sale_count.setPalette(palette)
        self.sale_count.setObjectName('sale_count')
        self.gridlayout.addWidget(self.sale_count, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayout)
        self.label_11.setObjectName('label_11')
        self.gridlayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.sale_income = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sale_income.setPalette(palette)
        self.sale_income.setObjectName('sale_income')
        self.gridlayout.addWidget(self.sale_income, 2, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayout)
        self.label_13.setObjectName('label_13')
        self.gridlayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.total_income = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.total_income.setPalette(palette)
        self.total_income.setObjectName('total_income')
        self.gridlayout.addWidget(self.total_income, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayout)
        self.label_15.setObjectName('label_15')
        self.gridlayout.addWidget(self.label_15, 3, 2, 1, 1)
        self.total_tax = QtGui.QLabel(self.gridLayout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.total_tax.setPalette(palette)
        self.total_tax.setObjectName('total_tax')
        self.gridlayout.addWidget(self.total_tax, 3, 3, 1, 1)
        self.label_today = QtGui.QLabel(self.gridLayout)
        self.label_today.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_today.setPalette(palette)
        self.label_today.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_today.setObjectName('label_today')
        self.gridlayout.addWidget(self.label_today, 0, 2, 1, 1)
        self.gridLayout_2 = QtGui.QWidget(reportForm)
        self.gridLayout_2.setGeometry(QtCore.QRect(60, 460, 471, 191))
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.gridlayout1 = QtGui.QGridLayout(self.gridLayout_2)
        self.gridlayout1.setObjectName('gridlayout1')
        self.label_2 = QtGui.QLabel(self.gridLayout_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        self.label_2.setObjectName('label_2')
        self.gridlayout1.addWidget(self.label_2, 0, 0, 1, 1)
        self.total_loaded_dvd = QtGui.QLabel(self.gridLayout_2)
        self.total_loaded_dvd.setObjectName('total_loaded_dvd')
        self.gridlayout1.addWidget(self.total_loaded_dvd, 0, 1, 1, 1)
        self.total_empty_slots = QtGui.QLabel(self.gridLayout_2)
        self.total_empty_slots.setObjectName('total_empty_slots')
        self.gridlayout1.addWidget(self.total_empty_slots, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayout_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        self.label_6.setObjectName('label_6')
        self.gridlayout1.addWidget(self.label_6, 1, 0, 1, 1)
        self.total_dvds_in = QtGui.QLabel(self.gridLayout_2)
        self.total_dvds_in.setObjectName('total_dvds_in')
        self.gridlayout1.addWidget(self.total_dvds_in, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayout_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        self.label_10.setObjectName('label_10')
        self.gridlayout1.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayout_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_12.setPalette(palette)
        self.label_12.setObjectName('label_12')
        self.gridlayout1.addWidget(self.label_12, 3, 0, 1, 1)
        self.total_dvds_out = QtGui.QLabel(self.gridLayout_2)
        self.total_dvds_out.setObjectName('total_dvds_out')
        self.gridlayout1.addWidget(self.total_dvds_out, 3, 1, 1, 1)
        self.gridLayout_3 = QtGui.QWidget(reportForm)
        self.gridLayout_3.setGeometry(QtCore.QRect(50, 680, 681, 191))
        self.gridLayout_3.setObjectName('gridLayout_3')
        self.gridlayout2 = QtGui.QGridLayout(self.gridLayout_3)
        self.gridlayout2.setObjectName('gridlayout2')
        self.label_3 = QtGui.QLabel(self.gridLayout_3)
        self.label_3.setMinimumSize(QtCore.QSize(165, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setObjectName('label_3')
        self.gridlayout2.addWidget(self.label_3, 1, 0, 1, 1)
        self.completed_rentals_week = QtGui.QLabel(self.gridLayout_3)
        self.completed_rentals_week.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.completed_rentals_week.setObjectName('completed_rentals_week')
        self.gridlayout2.addWidget(self.completed_rentals_week, 1, 1, 1, 1)
        self.completed_rentals_month = QtGui.QLabel(self.gridLayout_3)
        self.completed_rentals_month.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.completed_rentals_month.setObjectName('completed_rentals_month')
        self.gridlayout2.addWidget(self.completed_rentals_month, 1, 2, 1, 1)
        self.completed_rentals_year = QtGui.QLabel(self.gridLayout_3)
        self.completed_rentals_year.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.completed_rentals_year.setObjectName('completed_rentals_year')
        self.gridlayout2.addWidget(self.completed_rentals_year, 1, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayout_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        self.label_16.setObjectName('label_16')
        self.gridlayout2.addWidget(self.label_16, 2, 0, 1, 1)
        self.rental_income_week = QtGui.QLabel(self.gridLayout_3)
        self.rental_income_week.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.rental_income_week.setObjectName('rental_income_week')
        self.gridlayout2.addWidget(self.rental_income_week, 2, 1, 1, 1)
        self.rental_income_month = QtGui.QLabel(self.gridLayout_3)
        self.rental_income_month.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.rental_income_month.setObjectName('rental_income_month')
        self.gridlayout2.addWidget(self.rental_income_month, 2, 2, 1, 1)
        self.rental_income_year = QtGui.QLabel(self.gridLayout_3)
        self.rental_income_year.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.rental_income_year.setObjectName('rental_income_year')
        self.gridlayout2.addWidget(self.rental_income_year, 2, 3, 1, 1)
        self.initial_rentals_year = QtGui.QLabel(self.gridLayout_3)
        self.initial_rentals_year.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.initial_rentals_year.setObjectName('initial_rentals_year')
        self.gridlayout2.addWidget(self.initial_rentals_year, 3, 3, 1, 1)
        self.initial_rentals_month = QtGui.QLabel(self.gridLayout_3)
        self.initial_rentals_month.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.initial_rentals_month.setObjectName('initial_rentals_month')
        self.gridlayout2.addWidget(self.initial_rentals_month, 3, 2, 1, 1)
        self.initial_rentals_week = QtGui.QLabel(self.gridLayout_3)
        self.initial_rentals_week.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.initial_rentals_week.setObjectName('initial_rentals_week')
        self.gridlayout2.addWidget(self.initial_rentals_week, 3, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayout_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        self.label_23.setObjectName('label_23')
        self.gridlayout2.addWidget(self.label_23, 3, 0, 1, 1)
        self.sale_count_year = QtGui.QLabel(self.gridLayout_3)
        self.sale_count_year.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sale_count_year.setObjectName('sale_count_year')
        self.gridlayout2.addWidget(self.sale_count_year, 4, 3, 1, 1)
        self.sale_count_month = QtGui.QLabel(self.gridLayout_3)
        self.sale_count_month.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sale_count_month.setObjectName('sale_count_month')
        self.gridlayout2.addWidget(self.sale_count_month, 4, 2, 1, 1)
        self.sale_count_week = QtGui.QLabel(self.gridLayout_3)
        self.sale_count_week.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sale_count_week.setObjectName('sale_count_week')
        self.gridlayout2.addWidget(self.sale_count_week, 4, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayout_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_27.setPalette(palette)
        self.label_27.setObjectName('label_27')
        self.gridlayout2.addWidget(self.label_27, 4, 0, 1, 1)
        self.sale_income_year = QtGui.QLabel(self.gridLayout_3)
        self.sale_income_year.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sale_income_year.setObjectName('sale_income_year')
        self.gridlayout2.addWidget(self.sale_income_year, 5, 3, 1, 1)
        self.sale_income_month = QtGui.QLabel(self.gridLayout_3)
        self.sale_income_month.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sale_income_month.setObjectName('sale_income_month')
        self.gridlayout2.addWidget(self.sale_income_month, 5, 2, 1, 1)
        self.sale_income_week = QtGui.QLabel(self.gridLayout_3)
        self.sale_income_week.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sale_income_week.setObjectName('sale_income_week')
        self.gridlayout2.addWidget(self.sale_income_week, 5, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayout_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_31.setPalette(palette)
        self.label_31.setObjectName('label_31')
        self.gridlayout2.addWidget(self.label_31, 5, 0, 1, 1)
        self.label_y = QtGui.QLabel(self.gridLayout_3)
        self.label_y.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_y.setPalette(palette)
        self.label_y.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_y.setObjectName('label_y')
        self.gridlayout2.addWidget(self.label_y, 0, 1, 1, 1)
        self.label_m = QtGui.QLabel(self.gridLayout_3)
        self.label_m.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_m.setPalette(palette)
        self.label_m.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_m.setObjectName('label_m')
        self.gridlayout2.addWidget(self.label_m, 0, 2, 1, 1)
        self.label_w = QtGui.QLabel(self.gridLayout_3)
        self.label_w.setMinimumSize(QtCore.QSize(165, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_w.setPalette(palette)
        self.label_w.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_w.setObjectName('label_w')
        self.gridlayout2.addWidget(self.label_w, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QWidget(reportForm)
        self.horizontalLayout_2.setGeometry(QtCore.QRect(50, 920, 671, 81))
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.hboxlayout1 = QtGui.QHBoxLayout(self.horizontalLayout_2)
        self.hboxlayout1.setObjectName('hboxlayout1')
        self.retranslateUi(reportForm)
        QtCore.QMetaObject.connectSlotsByName(reportForm)

    
    def retranslateUi(self, reportForm):
        self.kiosk_id_label.setText(QtGui.QApplication.translate('reportForm', 'ID: ', None, QtGui.QApplication.UnicodeUTF8))
        self.kiosk_id_label_5.setText(QtGui.QApplication.translate('reportForm', ' | ', None, QtGui.QApplication.UnicodeUTF8))
        self.kiosk_id_label_3.setText(QtGui.QApplication.translate('reportForm', 'Capacity: ', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_pick_label.setText(QtGui.QApplication.translate('reportForm', 'Report', None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate('reportForm', 'Completed Rentals:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate('reportForm', 'Total Rental Income:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate('reportForm', 'Initial Rentals:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate('reportForm', 'Sales Count:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate('reportForm', 'Sales Income:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate('reportForm', 'Total Income:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate('reportForm', 'Total Tax:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_today.setText(QtGui.QApplication.translate('reportForm', 'Today: ', None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate('reportForm', 'Total loaded DVDs:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate('reportForm', 'Total Empty Slots:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate('reportForm', 'Total DVDs In:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate('reportForm', 'Total DVDs Out:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate('reportForm', 'Completed Rentals', None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate('reportForm', 'Rental Income', None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate('reportForm', 'Initial Rentals', None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate('reportForm', 'Sales Count', None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate('reportForm', 'Sales Income', None, QtGui.QApplication.UnicodeUTF8))
        self.label_y.setText(QtGui.QApplication.translate('reportForm', 'Current Week', None, QtGui.QApplication.UnicodeUTF8))
        self.label_m.setText(QtGui.QApplication.translate('reportForm', '  Current Month', None, QtGui.QApplication.UnicodeUTF8))
        self.label_w.setText(QtGui.QApplication.translate('reportForm', 'Current Year', None, QtGui.QApplication.UnicodeUTF8))


