# Source Generated with Decompyle++
# File: returnResultForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_returnResultForm(object):
    
    def setupUi(self, returnResultForm):
        returnResultForm.setObjectName('returnResultForm')
        returnResultForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 983).size()).expandedTo(returnResultForm.minimumSizeHint()))
        returnResultForm.setAutoFillBackground(True)
        self.txt_return_label = QtGui.QLabel(returnResultForm)
        self.txt_return_label.setGeometry(QtCore.QRect(60, 40, 341, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_return_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_return_label.setFont(font)
        self.txt_return_label.setObjectName('txt_return_label')
        self.txt_msg = QtGui.QLabel(returnResultForm)
        self.txt_msg.setGeometry(QtCore.QRect(100, 140, 561, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_msg.setFont(font)
        self.txt_msg.setScaledContents(False)
        self.txt_msg.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.txt_msg.setWordWrap(True)
        self.txt_msg.setObjectName('txt_msg')
        self.txt_return_option = QtGui.QLabel(returnResultForm)
        self.txt_return_option.setGeometry(QtCore.QRect(100, 410, 561, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_return_option.setFont(font)
        self.txt_return_option.setScaledContents(False)
        self.txt_return_option.setWordWrap(True)
        self.txt_return_option.setObjectName('txt_return_option')
        self.horizontalLayout = QtGui.QWidget(returnResultForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(60, 910, 651, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.retranslateUi(returnResultForm)
        QtCore.QMetaObject.connectSlotsByName(returnResultForm)

    
    def retranslateUi(self, returnResultForm):
        self.txt_return_label.setText(QtGui.QApplication.translate('returnResultForm', 'Return Disc', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_return_option.setText(QtGui.QApplication.translate('returnResultForm', 'Thank you!', None, QtGui.QApplication.UnicodeUTF8))


