# Source Generated with Decompyle++
# File: returnOptionForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_returnOptionForm(object):
    
    def setupUi(self, returnOptionForm):
        returnOptionForm.setObjectName('returnOptionForm')
        returnOptionForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 996).size()).expandedTo(returnOptionForm.minimumSizeHint()))
        returnOptionForm.setAutoFillBackground(True)
        self.txt_return_label = QtGui.QLabel(returnOptionForm)
        self.txt_return_label.setGeometry(QtCore.QRect(60, 40, 401, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_return_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_return_label.setFont(font)
        self.txt_return_label.setObjectName('txt_return_label')
        self.txt_msg = QtGui.QLabel(returnOptionForm)
        self.txt_msg.setGeometry(QtCore.QRect(100, 150, 561, 118))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txt_msg.setFont(font)
        self.txt_msg.setScaledContents(False)
        self.txt_msg.setWordWrap(True)
        self.txt_msg.setObjectName('txt_msg')
        self.txt_return_option = QtGui.QLabel(returnOptionForm)
        self.txt_return_option.setGeometry(QtCore.QRect(100, 410, 561, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_return_option.setFont(font)
        self.txt_return_option.setScaledContents(False)
        self.txt_return_option.setWordWrap(True)
        self.txt_return_option.setObjectName('txt_return_option')
        self.retranslateUi(returnOptionForm)
        QtCore.QMetaObject.connectSlotsByName(returnOptionForm)

    
    def retranslateUi(self, returnOptionForm):
        self.txt_return_label.setText(QtGui.QApplication.translate('returnOptionForm', 'Return Disc', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_return_option.setText(QtGui.QApplication.translate('returnOptionForm', 'Or return this Disc', None, QtGui.QApplication.UnicodeUTF8))


