# Source Generated with Decompyle++
# File: returnDiscListForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_returnDiscListForm(object):
    
    def setupUi(self, returnDiscListForm):
        returnDiscListForm.setObjectName('returnDiscListForm')
        returnDiscListForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 996).size()).expandedTo(returnDiscListForm.minimumSizeHint()))
        returnDiscListForm.setAutoFillBackground(True)
        self.txt_return_label = QtGui.QLabel(returnDiscListForm)
        self.txt_return_label.setGeometry(QtCore.QRect(60, 40, 361, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_return_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_return_label.setFont(font)
        self.txt_return_label.setObjectName('txt_return_label')
        self.txt_title = QtGui.QLabel(returnDiscListForm)
        self.txt_title.setGeometry(QtCore.QRect(60, 140, 601, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_title.setFont(font)
        self.txt_title.setScaledContents(False)
        self.txt_title.setWordWrap(True)
        self.txt_title.setObjectName('txt_title')
        self.txt_time_now_label = QtGui.QLabel(returnDiscListForm)
        self.txt_time_now_label.setGeometry(QtCore.QRect(70, 760, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txt_time_now_label.setFont(font)
        self.txt_time_now_label.setScaledContents(False)
        self.txt_time_now_label.setWordWrap(True)
        self.txt_time_now_label.setObjectName('txt_time_now_label')
        self.txt_time_now = QtGui.QLabel(returnDiscListForm)
        self.txt_time_now.setGeometry(QtCore.QRect(250, 760, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txt_time_now.setFont(font)
        self.txt_time_now.setScaledContents(False)
        self.txt_time_now.setWordWrap(True)
        self.txt_time_now.setObjectName('txt_time_now')
        self.retranslateUi(returnDiscListForm)
        QtCore.QMetaObject.connectSlotsByName(returnDiscListForm)

    
    def retranslateUi(self, returnDiscListForm):
        self.txt_return_label.setText(QtGui.QApplication.translate('returnDiscListForm', 'Return Disc', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_title.setText(QtGui.QApplication.translate('returnDiscListForm', 'The Discs You Rented', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_time_now_label.setText(QtGui.QApplication.translate('returnDiscListForm', 'Time Now:', None, QtGui.QApplication.UnicodeUTF8))


