# Source Generated with Decompyle++
# File: showAllSlotForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_showAllSlotForm(object):
    
    def setupUi(self, showAllSlotForm):
        showAllSlotForm.setObjectName('showAllSlotForm')
        showAllSlotForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(showAllSlotForm.minimumSizeHint()))
        showAllSlotForm.setMinimumSize(QtCore.QSize(768, 1024))
        showAllSlotForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        showAllSlotForm.setPalette(palette)
        showAllSlotForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        showAllSlotForm.setAutoFillBackground(True)
        self.txt_title_label = QtGui.QLabel(showAllSlotForm)
        self.txt_title_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_title_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_title_label.setFont(font)
        self.txt_title_label.setObjectName('txt_title_label')
        self.horizontalLayout = QtGui.QWidget(showAllSlotForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(40, 910, 691, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.txtbox_msg = QtGui.QLabel(showAllSlotForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(60, 120, 651, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setScaledContents(False)
        self.txtbox_msg.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txtbox_msg.setWordWrap(True)
        self.txtbox_msg.setObjectName('txtbox_msg')
        self.txtbox_key = QtGui.QLabel(showAllSlotForm)
        self.txtbox_key.setGeometry(QtCore.QRect(180, 120, 131, 38))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_key.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txtbox_key.setFont(font)
        self.txtbox_key.setScaledContents(False)
        self.txtbox_key.setObjectName('txtbox_key')
        self.txt_found = QtGui.QLabel(showAllSlotForm)
        self.txt_found.setGeometry(QtCore.QRect(40, 840, 71, 42))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_found.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txt_found.setFont(font)
        self.txt_found.setScaledContents(False)
        self.txt_found.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_found.setObjectName('txt_found')
        self.txt_found_label = QtGui.QLabel(showAllSlotForm)
        self.txt_found_label.setGeometry(QtCore.QRect(120, 840, 431, 38))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_found_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.txt_found_label.setFont(font)
        self.txt_found_label.setScaledContents(False)
        self.txt_found_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.txt_found_label.setObjectName('txt_found_label')
        self.retranslateUi(showAllSlotForm)
        QtCore.QMetaObject.connectSlotsByName(showAllSlotForm)

    
    def retranslateUi(self, showAllSlotForm):
        self.txt_title_label.setText(QtGui.QApplication.translate('showAllSlotForm', 'Slots', None, QtGui.QApplication.UnicodeUTF8))


