# Source Generated with Decompyle++
# File: superAdminOffsetAdj_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_superAdminOffsetAdjForm(object):
    
    def setupUi(self, superAdminOffsetAdjForm):
        superAdminOffsetAdjForm.setObjectName('superAdminOffsetAdjForm')
        superAdminOffsetAdjForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(superAdminOffsetAdjForm.minimumSizeHint()))
        superAdminOffsetAdjForm.setMinimumSize(QtCore.QSize(768, 1024))
        superAdminOffsetAdjForm.setMaximumSize(QtCore.QSize(768, 1024))
        superAdminOffsetAdjForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        superAdminOffsetAdjForm.setAutoFillBackground(True)
        self.txt_admin_label = QtGui.QLabel(superAdminOffsetAdjForm)
        self.txt_admin_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_admin_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_admin_label.setFont(font)
        self.txt_admin_label.setObjectName('txt_admin_label')
        self.frame = QtGui.QFrame(superAdminOffsetAdjForm)
        self.frame.setGeometry(QtCore.QRect(79, 159, 601, 491))
        self.frame.setObjectName('frame')
        self.txt_label = QtGui.QLabel(self.frame)
        self.txt_label.setGeometry(QtCore.QRect(10, 10, 571, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_label.setFont(font)
        self.txt_label.setObjectName('txt_label')
        self.txt_title = QtGui.QLabel(self.frame)
        self.txt_title.setGeometry(QtCore.QRect(10, 70, 571, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_title.setFont(font)
        self.txt_title.setObjectName('txt_title')
        self.txt_offset_label = QtGui.QLabel(self.frame)
        self.txt_offset_label.setGeometry(QtCore.QRect(10, 130, 231, 44))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_offset_label.setFont(font)
        self.txt_offset_label.setObjectName('txt_offset_label')
        self.txt_offset = QtGui.QLabel(self.frame)
        self.txt_offset.setGeometry(QtCore.QRect(250, 130, 231, 44))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_offset.setFont(font)
        self.txt_offset.setObjectName('txt_offset')
        self.txt_delta_label = QtGui.QLabel(self.frame)
        self.txt_delta_label.setGeometry(QtCore.QRect(10, 190, 231, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_delta_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_delta_label.setFont(font)
        self.txt_delta_label.setObjectName('txt_delta_label')
        self.txt_delta = QtGui.QLabel(self.frame)
        self.txt_delta.setGeometry(QtCore.QRect(250, 190, 231, 44))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_delta.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_delta.setFont(font)
        self.txt_delta.setObjectName('txt_delta')
        self.txt_up_label = QtGui.QLabel(self.frame)
        self.txt_up_label.setGeometry(QtCore.QRect(100, 280, 51, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_up_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.txt_up_label.setFont(font)
        self.txt_up_label.setObjectName('txt_up_label')
        self.horizontalLayout = QtGui.QWidget(self.frame)
        self.horizontalLayout.setGeometry(QtCore.QRect(39, 390, 521, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.horizontalLayout_2 = QtGui.QWidget(self.frame)
        self.horizontalLayout_2.setGeometry(QtCore.QRect(139, 249, 281, 111))
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.hboxlayout1 = QtGui.QHBoxLayout(self.horizontalLayout_2)
        self.hboxlayout1.setSpacing(30)
        self.hboxlayout1.setContentsMargins(4, -1, 4, -1)
        self.hboxlayout1.setObjectName('hboxlayout1')
        self.txt_process = QtGui.QLabel(self.frame)
        self.txt_process.setGeometry(QtCore.QRect(10, 160, 571, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_process.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.txt_process.setFont(font)
        self.txt_process.setObjectName('txt_process')
        self.txt_down_label = QtGui.QLabel(superAdminOffsetAdjForm)
        self.txt_down_label.setGeometry(QtCore.QRect(500, 440, 51, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_down_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.txt_down_label.setFont(font)
        self.txt_down_label.setObjectName('txt_down_label')
        self.retranslateUi(superAdminOffsetAdjForm)
        QtCore.QMetaObject.connectSlotsByName(superAdminOffsetAdjForm)

    
    def retranslateUi(self, superAdminOffsetAdjForm):
        self.txt_admin_label.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', 'Super Admin', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_label.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', 'Offset Adjustment', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_title.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', 'Top Offset', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_offset_label.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', 'Older Offset :', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_delta_label.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', 'Now set to :', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_up_label.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', '+10', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_down_label.setText(QtGui.QApplication.translate('superAdminOffsetAdjForm', '-10', None, QtGui.QApplication.UnicodeUTF8))


