# Source Generated with Decompyle++
# File: swipecard_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_checkoutSwipeCardForm(object):
    
    def setupUi(self, checkoutSwipeCardForm):
        checkoutSwipeCardForm.setObjectName('checkoutSwipeCardForm')
        checkoutSwipeCardForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(checkoutSwipeCardForm.minimumSizeHint()))
        checkoutSwipeCardForm.setMinimumSize(QtCore.QSize(768, 1024))
        checkoutSwipeCardForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        checkoutSwipeCardForm.setPalette(palette)
        checkoutSwipeCardForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        checkoutSwipeCardForm.setAutoFillBackground(True)
        self.txt_card_label = QtGui.QLabel(checkoutSwipeCardForm)
        self.txt_card_label.setGeometry(QtCore.QRect(50, 30, 411, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_card_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.txt_card_label.setFont(font)
        self.txt_card_label.setObjectName('txt_card_label')
        self.horizontalLayout = QtGui.QWidget(checkoutSwipeCardForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(50, 920, 671, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.txtbox_msg = QtGui.QLabel(checkoutSwipeCardForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(90, 120, 571, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setScaledContents(False)
        self.txtbox_msg.setWordWrap(True)
        self.txtbox_msg.setObjectName('txtbox_msg')
        self.swf_credit_cars = QtGui.QLabel(checkoutSwipeCardForm)
        self.swf_credit_cars.setGeometry(QtCore.QRect(103, 260, 541, 101))
        self.swf_credit_cars.setObjectName('swf_credit_cars')
        self.splitter = QtGui.QSplitter(checkoutSwipeCardForm)
        self.splitter.setGeometry(QtCore.QRect(50, 840, 671, 40))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName('splitter')
        self.txt_flag3 = QtGui.QLabel(self.splitter)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_flag3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.txt_flag3.setFont(font)
        self.txt_flag3.setObjectName('txt_flag3')
        self.txt_flag4 = QtGui.QLabel(self.splitter)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_flag4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.txt_flag4.setFont(font)
        self.txt_flag4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txt_flag4.setObjectName('txt_flag4')
        self.splitter_2 = QtGui.QSplitter(checkoutSwipeCardForm)
        self.splitter_2.setGeometry(QtCore.QRect(51, 111, 671, 40))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName('splitter_2')
        self.txt_flag1 = QtGui.QLabel(self.splitter_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_flag1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.txt_flag1.setFont(font)
        self.txt_flag1.setObjectName('txt_flag1')
        self.txt_flag2 = QtGui.QLabel(self.splitter_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 154, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_flag2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.txt_flag2.setFont(font)
        self.txt_flag2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txt_flag2.setObjectName('txt_flag2')
        self.txt_deposit_amount_label = QtGui.QLabel(checkoutSwipeCardForm)
        self.txt_deposit_amount_label.setGeometry(QtCore.QRect(90, 190, 571, 60))
        self.txt_deposit_amount_label.setWordWrap(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_deposit_amount_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily('Sans Serif')
        font.setPointSize(14)
        font.setWeight(60)
        font.setBold(True)
        self.txt_deposit_amount_label.setFont(font)
        self.txt_deposit_amount_label.setObjectName('txt_deposit_amount_label')
        self.retranslateUi(checkoutSwipeCardForm)
        QtCore.QMetaObject.connectSlotsByName(checkoutSwipeCardForm)

    
    def retranslateUi(self, checkoutSwipeCardForm):
        self.txt_card_label.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', 'Swipe Card', None, QtGui.QApplication.UnicodeUTF8))
        self.txtbox_msg.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', 'Please swipe your credit card to take your Disc(s)', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_flag3.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', 'Test Mode', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_flag4.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', 'Test Mode', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_flag1.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', 'Test Mode', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_flag2.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', 'Test Mode', None, QtGui.QApplication.UnicodeUTF8))
        self.txt_deposit_amount_label.setText(QtGui.QApplication.translate('checkoutSwipeCardForm', '', None, QtGui.QApplication.UnicodeUTF8))


