# Source Generated with Decompyle++
# File: unloadResultForm_ui.pyc (Python 2.5)

from PyQt4 import QtCore, QtGui

class Ui_unloadResultForm(object):
    
    def setupUi(self, unloadResultForm):
        unloadResultForm.setObjectName('unloadResultForm')
        unloadResultForm.resize(QtCore.QSize(QtCore.QRect(0, 0, 768, 1024).size()).expandedTo(unloadResultForm.minimumSizeHint()))
        unloadResultForm.setMinimumSize(QtCore.QSize(768, 1024))
        unloadResultForm.setMaximumSize(QtCore.QSize(768, 1024))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        unloadResultForm.setPalette(palette)
        unloadResultForm.setWindowIcon(QtGui.QIcon('../../../../.designer/backup'))
        unloadResultForm.setAutoFillBackground(True)
        self.txt_unload_label = QtGui.QLabel(unloadResultForm)
        self.txt_unload_label.setGeometry(QtCore.QRect(50, 30, 481, 56))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_unload_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_unload_label.setFont(font)
        self.txt_unload_label.setObjectName('txt_unload_label')
        self.horizontalLayout = QtGui.QWidget(unloadResultForm)
        self.horizontalLayout.setGeometry(QtCore.QRect(40, 910, 691, 91))
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.hboxlayout = QtGui.QHBoxLayout(self.horizontalLayout)
        self.hboxlayout.setObjectName('hboxlayout')
        self.txtbox_msg = QtGui.QLabel(unloadResultForm)
        self.txtbox_msg.setGeometry(QtCore.QRect(60, 140, 651, 691))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 96, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 125, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txtbox_msg.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.txtbox_msg.setFont(font)
        self.txtbox_msg.setScaledContents(False)
        self.txtbox_msg.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.txtbox_msg.setWordWrap(True)
        self.txtbox_msg.setObjectName('txtbox_msg')
        self.retranslateUi(unloadResultForm)
        QtCore.QMetaObject.connectSlotsByName(unloadResultForm)

    
    def retranslateUi(self, unloadResultForm):
        self.txt_unload_label.setText(QtGui.QApplication.translate('unloadResultForm', 'Unload', None, QtGui.QApplication.UnicodeUTF8))


